name: spence
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  http: ^1.2.2
  lottie: ^3.3.1
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.1
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.14.0
  workmanager: ^0.5.2
  fl_chart: ^0.70.2
  camera: ^0.11.1
  image_picker: ^1.1.2
  device_preview: ^1.2.0
  google_ml_kit: ^0.19.0
  image: ^4.5.3
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  timezone: ^0.10.0
  permission_handler: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/spence.svg
    - assets/light.svg
    - assets/dark.svg
    - assets/pattern.svg
    - assets/bubo.svg
    - assets/bubo_dark.svg
    - assets/predict.svg
    - assets/happy.svg
    - assets/happy.json
    - assets/spence_dark.svg
    - assets/predict_dark.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


