// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqazJyDiF4gOezLnsXq6b5z3p4J4vv0xk',
    appId: '1:817575513079:web:dff88f162a175815017cf2',
    messagingSenderId: '817575513079',
    projectId: 'spencev2-3b372',
    authDomain: 'spencev2-3b372.firebaseapp.com',
    storageBucket: 'spencev2-3b372.firebasestorage.app',
    measurementId: 'G-X7KPJGGV9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjuYGfBsCEwYRF_t11CSdcWpi6vmlmdA',
    appId: '1:817575513079:android:1f0f8d6edffac053017cf2',
    messagingSenderId: '817575513079',
    projectId: 'spencev2-3b372',
    storageBucket: 'spencev2-3b372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHaJCtuL9QfzZeyVzZwabv0wWIYPul40',
    appId: '1:817575513079:ios:3801271720e70551017cf2',
    messagingSenderId: '817575513079',
    projectId: 'spencev2-3b372',
    storageBucket: 'spencev2-3b372.firebasestorage.app',
    iosBundleId: 'com.example.spence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdHaJCtuL9QfzZeyVzZwabv0wWIYPul40',
    appId: '1:817575513079:ios:3801271720e70551017cf2',
    messagingSenderId: '817575513079',
    projectId: 'spencev2-3b372',
    storageBucket: 'spencev2-3b372.firebasestorage.app',
    iosBundleId: 'com.example.spence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqazJyDiF4gOezLnsXq6b5z3p4J4vv0xk',
    appId: '1:817575513079:web:deaaea32c64b07b9017cf2',
    messagingSenderId: '817575513079',
    projectId: 'spencev2-3b372',
    authDomain: 'spencev2-3b372.firebaseapp.com',
    storageBucket: 'spencev2-3b372.firebasestorage.app',
    measurementId: 'G-KVTT1PVTPL',
  );
}
